server:
  port: 8087

spring:
  application:
    name: arya-banking-auth-service
    database: auth

  config:
    import: configserver:http://localhost:8090

  kafka:
    bootstrap-servers: localhost:9092   # kafka:29092 in Docker
    properties:
      schema.registry.url: http://localhost:8081

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.token-uri}
        registration:
          auth-service-client:
            provider: keycloak
            client-id: auth-service-client
            client-secret: ${AUTH.SERVICE.CLIENT.SECRET}
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.jwk-set-uri}

app:
  security:
    client-registrationId: auth-service-client
  config:
    keycloak:
      client-id: arya-banking-auth-client
      client-secret: ${ARYA.BANKING.AUTH.CLIENT.SECRET}
